name: Test and Build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Pull to runner
      uses: actions/checkout@v3
      
    - name: Install nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies    
      run: npm ci

    - name: Run test    
      run: npm run test
  
  lint:
    needs: test
    runs-on: ubuntu-latest
    steps: 
    - name: Pull to runner
      uses: actions/checkout@v3
      
    - name: Install nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies    
      run: npm ci

    - name: Run lint    
      run: npm run lint

  build:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps: 
    - name: Pull to runner
      uses: actions/checkout@v3
      
    - name: Install nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies    
      run: npm ci

    - name: Build    
      run: npm run build

  deploy:
    needs: [test, lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Dummy deployment
        echo: "Deployment on GCP!!"